
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Package:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Install Prerequisites
      # use jing for validation instead of xmllint
      run: |-
        rake build_dependencies:install
        zypper --non-interactive install --no-recommends jing

    # just for easier debugging...
    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Package Build
      run: yast-ci-ruby -o package

    - name: Validate XML
      # install the built RPM and validate the XML using jing
      run: |-
        rpm -iv --force --nodeps /usr/src/packages/RPMS/*/*.rpm
        XML_FILES=$(rpm -qpl /usr/src/packages/RPMS/*/*.rpm | grep "\.xml$")
        echo "Validating ${XML_FILES}..."
        jing /usr/share/YaST2/control/control.rng $XML_FILES && echo "OK"
